export const trabajador_planilla_model = {
   trabajador_id:"",
   contrato_id:"",
   tipo_contrato:"",
   periodo:"",
   tipo_documento: "",
   numero_documento: "",
   nombres_apellidos: "",
   area: "",
   afp: "",
   fecha_ingreso: "",
   dias_labor: 0,
   sueldo_basico: 0,
   sueldo_del_mes: 0,
   asig_fam: 0,
   descanso_medico: 0,
   licencia_con_goce_de_haber: 0,
   licencia_sin_goce_de_haber: 0,
   vacaciones: 0,
   gratificacion: 0,
   cts: 0,
   h_extras_primera_quincena: 0,
   h_extras_segunda_quincena: 0,
   faltas_primera_quincena: 0,
   faltas_segunda_quincena: 0,
   tardanza_primera_quincena: 0,
   tardanza_segunda_quincena: 0,
   bono_primera_quincena: 0,
   bono_segunda_quincena: 0,
   sueldo_bruto: 0,
   onp: 0,
   eps_primera_quincena: 0,
   eps_segunda_quincena: 0,
   afp_ap_oblig: 0,
   seguro: 0,
   comision: 0,
   quinta_categoria: 0,
   total_descuentos: 0,
   sueldo_neto: 0,
   sueldo_quincenal: 0,
   adelanto_prestamo: 0,
   saldo_por_pagar: 0,
   filial_id:"",
   banco:"",
   numero_cuenta:"",
   sueldos_brutos_obtenidos:[],
   info_detalle: {
      descanso_med: [],
      lic_goce: [],
      lic_sin_goce: [],
      vacaciones: [],
      horas_e_pq: [],
      horas_e_sq: [],
      faltas_pq: [],
      faltas_sq: [],
      tardanza_pq: [],
      tardanza_sq: [],
      bonos_pq: [],
      bonos_sq: [],
      prestamos: [],
   },
};
