export const trabajador_rxh_model = () => ({
   // datos no nulos
   trabajador_id: 0,
   tipo_contrato: "",
   contrato_id:0,
   periodo: "",
   tipo_documento: "",
   numero_documento: "",
   nombres_apellidos: "",
   area: "",
   fecha_ingreso: "",
   dias_labor: 0,
   sueldo_basico: 0,
   sueldo_del_mes: 0,
   vacaciones: 0,
   vacaciones_vendidas:0,
   h_extras_primera_quincena: 0,
   h_extras_segunda_quincena: 0,
   faltas_primera_quincena: 0,
   faltas_segunda_quincena: 0,
   tardanza_primera_quincena: 0,
   tardanza_segunda_quincena: 0,
   bono_primera_quincena: 0,
   bono_segunda_quincena: 0,
   sueldo_neto: 0,
   sueldo_quincenal: 0,
   adelantos_ids:[],
   adelanto_prestamo:0,
   saldo_por_pagar: 0,
   banco:"",
   numero_cuenta:"",
   ruc:"",
   domiciliado:true,
});
